name: Publish

on:
  release:
    types: [created]

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  publish_github:
    name: Publish to GitHub Releases
    strategy:
      matrix:
        runner:
          - windows-latest  # windows
          - macos-latest    # macos
          - ubuntu-latest   # linux
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bazel build ...
      - name: Test
        run: bazel test ...